import os
import re

# Specify the folder path
folder = "HGWells"
file = "The Time Machine"


def process_book(file_name, folder_path):

    # Read the file content
    with open(os.path.join(folder_path, file_name), "r", encoding="utf-8") as file:
        stringInput = file.read()

    # Use regex to capture full chapter content
    # chapters = re.findall(r"(CHAPTER\b.*?)(?=CHAPTER|\Z)", stringInput, re.DOTALL)
    chapters = re.split(r"(?m)^[ ]{,5}[XVI]{1,10}\.$", stringInput)

    # Ensure the output folder exists
    output_folder = os.path.join(folder_path, "Chapters")
    os.makedirs(output_folder, exist_ok=True)

    # Write each chapter to a separate file
    for i, chapter in enumerate(chapters, start=1):
        new_file = os.path.join(output_folder, f"{file_name} Ch{i - 1}.txt")
        with open(new_file, "w", encoding="utf-8") as file:
            file.write(chapter.strip())  # Trim extra spaces

    print(f"Successfully split {len(chapters)} chapters into {output_folder}")

# List all files in the folder (generated by chatGPT)
# files = [f for f in os.listdir(folder) if os.path.isfile(os.path.join(folder, f))]
# for file in files:
#     print(f"Processing {file}...")
#     process_book(file, folder)
process_book(file, folder)